name: 'Auto Author Assign'

on:
  issues:
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: bernhold/auto-author-assign@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
